### PR TITLE
Implement Filter Functionality in Repos Component

### PR DESCRIPTION
**Pull request by AdarshRaj241408**
## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
This update introduces a filtering mechanism for the Repos component, allowing users to filter repositories based on specific criteria. A new FilterModal component has been added to enable users to set filters for:

- Language: Filter repositories by programming language.
- Minimum Stars: Specify the minimum number of stars a repository must have.
- Minimum Forks: Specify the minimum number of forks a repository must have.

Fixes #(issue)

## Type of change

- [ no] Bug fix (non-breaking change which fixes an issue)
- [yes ] New feature (non-breaking change which adds functionality)

## Checklist:

- [yes ] My code follows the style guidelines of this project
- [ yes] I have performed a self-review of my own code
- [yes ] I have commented my code, particularly in hard-to-understand areas
- [ yes] My changes generate no new warnings
- [ yes] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable):
image

### CODE REVIEW

**Comment by AdarshRaj241408** [comment]
The once applied filters can now be removed with the clear filters button. And opening and closing the filter prompt does not remove the previouslt typed filter inputs.

**Comment by AdarshRaj241408** [comment]
Already had a PR #53 I have taken the feedback and made the required changes this is part of the issue #46

**Review by Bashamega — CHANGES_REQUESTED** [review]
Hello:)
I have left a comment. I will continue to review when the API is fixed :)

**Review by Bashamega — APPROVED** [review]
Great work

**Pull request merged**
